name: nvr_forget
description: "An app for people with dementia."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-92.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_sound: ^9.2.13
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  path_provider: ^2.1.2
  record_mp3: ^3.0.0
  simple_gradient_text: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/Hamburger.svg
    - assets/robot.png
    - assets/user.png